app/base/models.py
import uuid

from bcrypt import gensalt, hashpw
from flask_login import UserMixin
from flask import session

from core import database
from flask_app import login_manager


@login_manager.user_loader
def user_loader(_id):
    return User.objects.get(_id=_id)


@login_manager.request_loader
def request_loader(request):
    username = request.form.get("username")
    if not username:
        return
    return User.objects.get(username=username)


class UserQuerySet:
    @classmethod
    def get(cls, **kwargs):
        data = database.get_collection("Users").find_one(kwargs)
        if data is not None:
            return User(**data)


class User(UserMixin):
    objects = UserQuerySet

    def __init__(self, username, email, password, _id=None):
        self.username = username
        self.email = email
        self.password = password
        self._id = uuid.uuid4().hex if _id is None else _id

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return self._id

    @classmethod
    def register(cls, username, email, password):
        user = cls.objects.get(email=email)
        if user is None:
            cls.create(username=username, email=email, password=password)
            session["email"] = email
            return True
        return False

    @classmethod
    def create(cls, **kwargs):
        kwargs["_id"] = uuid.uuid4().hex
        password = kwargs.get("password")
        if password:
            kwargs["password"] = hashpw(password.encode("utf8"), gensalt())
        return database.get_collection("Users").insert_one(kwargs)

app/base/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField


class LoginForm(FlaskForm):
    username = StringField("Username", id="username_login")
    password = PasswordField("Password", id="pwd_login")


class CreateAccountForm(FlaskForm):
    username = StringField("Username", id="username_create")
    email = StringField("Email")
    password = PasswordField("Password", id="pwd_create")

app/base/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    "base_blueprint",
    __name__,
    url_prefix="",
    template_folder="templates",
    static_folder="static",
)

app/base/routes.py
from bcrypt import checkpw
from flask import jsonify, render_template, redirect, request, url_for, abort
from flask_login import current_user, login_required, login_user, logout_user
from jinja2 import TemplateNotFound

from flask_app import login_manager
from app.base import blueprint
from app.base.forms import LoginForm, CreateAccountForm
from app.base.models import User


@blueprint.route("/admin")
def admin():
    if current_user.is_authenticated:
        return render_template("index1.html")
    return redirect(url_for("base_blueprint.login"))


@blueprint.route("/<template>")
@login_required
def route_template(template):
    try:
        return render_template(template + ".html")
    except TemplateNotFound:
        raise abort(404)


@blueprint.route("/fixed_<template>")
@login_required
def route_fixed_template(template):
    return render_template("fixed/fixed_{}.html".format(template))


@blueprint.route("/page_<error>")
def route_errors(error):
    return render_template("errors/page_{}.html".format(error))


@blueprint.route("/login", methods=["GET", "POST"])
def login():
    login_form = LoginForm(request.form)
    create_account_form = CreateAccountForm(request.form)
    if "login" in request.form:
        username = request.form["username"]
        password = request.form["password"]
        user = User.objects.get(username=username)
        if user and checkpw(password.encode("utf8"), user.password):
            login_user(user)
            return redirect(url_for("base_blueprint.admin"))
        return render_template("errors/page_403.html")
    if not current_user.is_authenticated:
        return render_template(
            "login/login.html",
            login_form=login_form,
            create_account_form=create_account_form,
        )
    return redirect(url_for("base_blueprint.admin"))


@blueprint.route("/create_user", methods=["POST"])
def create_user():
    User.create(**request.form)
    return jsonify("success")


@blueprint.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("base_blueprint.login"))


@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template("errors/page_403.html"), 403


@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template("errors/page_403.html"), 403


@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template("errors/page_404.html"), 404


@blueprint.errorhandler(500)
def internal_error(error):
    return render_template("errors/page_500.html"), 500

app/base/templates/base_site.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
      {% block meta %}
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}" type="image/ico" />
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
      {% endblock meta %}

      <title>Covid 19 Romania | {% block title %}{% endblock %}</title>

      {% block stylesheets %}
        <!-- Bootstrap -->
        <link href="{{ url_for('static', filename='vendors/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="{{ url_for('static', filename='vendors/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
        <!-- NProgress -->
        <link href="{{ url_for('static', filename='vendors/nprogress/nprogress.css') }}" rel="stylesheet">
        <!-- bootstrap-daterangepicker -->
        <link href="{{ url_for('static', filename='vendors/bootstrap-daterangepicker/daterangepicker.css') }}" rel="stylesheet">
        <!-- iCheck -->
        <link href="{{ url_for('static', filename='vendors/iCheck/skins/flat/green.css') }}" rel="stylesheet">
        <!-- bootstrap-progressbar -->
        <link href="{{ url_for('static', filename='vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css') }}" rel="stylesheet">
        <!-- JQVMap -->
        <link href="{{ url_for('static', filename='vendors/jqvmap/dist/jqvmap.min.css') }}" rel="stylesheet"/>
        <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Oswald" />
      {% endblock stylesheets %}
      <!-- Custom Theme Style -->
      <link href="{{ url_for('static', filename='build/css/custom.min.css') }}" rel="stylesheet">
    {% endblock head %}
  </head>

  <body class="{% block body_class %}nav-md {% endblock body_class %}" {% block extra_body_attrs %}{% endblock %}>
    {% block body %}
      <div class="container body">
        <div class="main_container">

          {% block sidebar %}
            <div class="col-md-3 left_col {% block sidebar_class %}{% endblock sidebar_class %}">
              {% include "site_template/sidebar.html" %}
            </div>
          {% endblock sidebar %}

          {% block top_navigation %}
            <div class="top_nav">
              {% include "site_template/top_navigation.html" %}
            </div>
          {% endblock top_navigation %}

          {% block content %}
            <!-- {{ content }} -->
          {% endblock content %}

          {% block footer %}
            <footer>
              {% include "site_template/footer.html" %}
            </footer>
          {% endblock footer %}
        </div>
      </div>

      {% block javascripts %}
        <!-- jQuery -->
        <script src="{{ url_for('static', filename='vendors/jquery/dist/jquery.min.js') }}"></script>
        <!-- Bootstrap -->
        <script src="{{ url_for('static', filename='vendors/bootstrap/dist/js/bootstrap.min.js') }}"></script>
        <!-- FastClick -->
        <script src="{{ url_for('static', filename='vendors/fastclick/lib/fastclick.js') }}"></script>
        <!-- NProgress -->
        <script src="{{ url_for('static', filename='vendors/nprogress/nprogress.js') }}"></script>
        <!-- bootstrap-progressbar -->
        <script src="{{ url_for('static', filename='vendors/bootstrap-progressbar/bootstrap-progressbar.min.js') }}"></script>
        <!-- iCheck -->
        <script src="{{ url_for('static', filename='vendors/iCheck/icheck.min.js') }}"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="{{ url_for('static', filename='vendors/moment/min/moment.min.js') }}"></script>
        <script src="{{ url_for('static', filename='vendors/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
        <!-- bootstrap-wysiwyg -->
        <script src="{{ url_for('static', filename='vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js') }}"></script>
        <script src="{{ url_for('static', filename='vendors/jquery.hotkeys/jquery.hotkeys.js') }}"></script>
        <script src="{{ url_for('static', filename='vendors/google-code-prettify/src/prettify.js') }}"></script>
        <!-- jQuery Tags Input -->
        <script src="{{ url_for('static', filename='vendors/jquery.tagsinput/src/jquery.tagsinput.js') }}"></script>
        <!-- Switchery -->
        <script src="{{ url_for('static', filename='vendors/switchery/dist/switchery.min.js') }}"></script>
        <!-- Select2 -->
        <script src="{{ url_for('static', filename='vendors/select2/dist/js/select2.full.min.js') }}"></script>
        <!-- Autosize -->
        <script src="{{ url_for('static', filename='vendors/autosize/dist/autosize.min.js') }}"></script>
        <!-- jQuery autocomplete -->
        <script src="{{ url_for('static', filename='vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js') }}"></script>
        <!-- starrr -->
        <script src="{{ url_for('static', filename='vendors/starrr/dist/starrr.js') }}"></script>
      {% endblock %}
      <!-- Custom Theme Scripts -->
      <script src="{{ url_for('static', filename='build/js/custom.js') }}"></script>
    {% endblock body %}
  </body>
</html>

app/base/templates/fixed/fixed_footer.html
{% extends "base_site.html" %}

{% block title %} Fixed Footer {% endblock title %}

{% block stylesheets %}
  {{ super() }}
  <!-- jQuery custom content scroller -->
  <link href="{{ url_for('static', filename='vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css') }}" rel="stylesheet"/>
{% endblock stylesheets %}

{% block body_class %}nav-md footer_fixed{% endblock body_class %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Fixed Footer <small> Just add class <strong>footer_fixed</strong></small></h3>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ super() }}
  <!-- jQuery custom content scroller -->
  <script src="{{ url_for('static', filename='vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js') }}"></script>
{% endblock javascripts %}

app/base/templates/fixed/fixed_sidebar.html
{% extends "base_site.html" %}

{% block title %} Fixed Sidebar {% endblock title %}

{% block stylesheets %}
  {{ super() }}
  <!-- jQuery custom content scroller -->
  <link href="{{ url_for('static', filename='vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css') }}" rel="stylesheet"/>
{% endblock stylesheets %}

{% block sidebar_class %}nav-md menu_fixed{% endblock sidebar_class %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Fixed Sidebar <small> Just add class <strong>menu_fixed</strong></small></h3>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ super() }}
  <!-- jQuery custom content scroller -->
  <script src="{{ url_for('static', filename='vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js') }}"></script>
{% endblock javascripts %}

app/base/templates/login/login.html
{% extends "base_site.html" %}

{% block title %} Login {% endblock title %}

{% block stylesheets %}
  {{ super() }}
  <!-- Animate.css -->
  <link href="{{ url_for('static', filename='vendors/animate.css/animate.min.css') }}" rel="stylesheet">
  <!-- Alertify -->
  <link href="{{ url_for('static', filename='vendors/alertifyjs/css/alertify.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendors/alertifyjs/css/custom.alertify.css') }}" rel="stylesheet">
{% endblock stylesheets %}

{% block body_class %}login{% endblock body_class %}

{% block body %}
  <!-- jQuery -->
  <script src="{{ url_for('static', filename='vendors/jquery/dist/jquery.min.js') }}"></script>
  <!-- Alertify -->
  <script src="{{ url_for('static', filename='vendors/alertifyjs/alertify.min.js') }}"></script>
  <!-- Parsley -->
  <script src="{{ url_for('static', filename='vendors/parsleyjs/dist/parsley.min.js') }}"></script>
  <!-- Login -->
  <script src="{{ url_for('static', filename='build/js/login.js') }}"></script>
  <div>
{#    <a class="hiddenanchor" id="signup"></a>#}
    <a class="hiddenanchor" id="signin"></a>
    <div class="login_wrapper">
      <div class="animate form login_form">
        <section class="login_content">
          <form data-parsley-validate method="post">
            <h1>Login</h1>
            {% for field in login_form if field.widget.input_type != 'hidden'  %}
              <div>
                {{ field(class="form-control required", placeholder=field.label.text) }}
              </div>
            {% endfor %}
            <div>
            <button type="submit" class="btn btn-default submit" name="login">Log in</button>
            </div>
            <div class="clearfix"></div>
{#            <div class="separator">#}
{#              <p class="change_link">New to site?#}
{#                <a href="#signup" class="to_register"> Create Account </a>#}
{#              </p>#}
              <div class="clearfix"></div>
              <br/>
              <div>
                <h1><i class="fa fa-lock"></i> Hey there! </h1>
                <p>©2020 All Rights Reserved. Gentelella Alela! is a Bootstrap 3 template. Privacy and Terms</p>
              </div>
            </div>
          </form>
        </section>
      </div>
{#      <div id="register" class="animate form registration_form">#}
{#        <section class="login_content">#}
{#          <form data-parsley-validate id="create-user-form" method="post">#}
{#            <h1>Create Account</h1>#}
{#            {% for field in create_account_form if field.widget.input_type != 'hidden'  %}#}
{#              <div>#}
{#                {{ field(class="form-control required", placeholder=field.label.text) }}#}
{#              </div>#}
{#            {% endfor %}#}
{#            <div>#}
{#              <button type="button" class="btn btn-default" onclick="signup()">Sign up</button>#}
{#            </div>#}
{#            <div class="clearfix"></div>#}
{#            <div class="separator">#}
{#              <p class="change_link">Already a member ?#}
{#                <a href="#signin" id="login-button" class="to_register"> Log in </a>#}
{#              </p>#}
{#              <div class="clearfix"></div>#}
{#              <br/>#}
{#              <div>#}
{#                <h1><i class="fa fa-lock"></i> Gentelella Alela!</h1>#}
{#                <p>©2016 All Rights Reserved. Gentelella Alela! is a Bootstrap 3 template. Privacy and Terms</p>#}
{#              </div>#}
{#            </div>#}
{#          </form>#}
{#        </section>#}
{#      </div>#}
    </div>
  </div>
{% endblock body %}

app/base/templates/plain_page.html
{% extends "base_site.html" %}

{% block title %} Plain Page {% endblock title %}

{% block stylesheets %}
  {{ super() }}
{% endblock stylesheets %}

{% block content %}
    <div class="right_col" role="main">
      <div class="">
        <div class="page-title">
          <div class="title_left">
            <h3>Plain Page</h3>
          </div>

          <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <button class="btn btn-default" type="button">Go!</button>
                </span>
              </div>
            </div>
          </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>Plain Page</h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="#">Settings 1</a>
                      </li>
                      <li><a href="#">Settings 2</a>
                      </li>
                    </ul>
                  </li>
                  <li><a class="close-link"><i class="fa fa-close"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
                  Add content to the page ...
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

{% block javascripts %}
  {{ super() }}
{% endblock javascripts %}

app/base/templates/site_template/footer.html
<div class="pull-right">
  SIMPLTON - Based on Template by <a href="https://colorlib.com/wp/free-bootstrap-admin-dashboard-templates/">Colorlib</a>
</div>
<div class="clearfix"></div>

app/base/templates/site_template/parts/sidebar_item.html
<li>
    <a>
        <i class="fa fa-{{ icon }}"></i> {{ title }}
        <span class="fa fa-chevron-down"></span>
    </a>
    <ul class="nav child_menu">
        {% for item in items %}
            <li><a href="/{{ title|lower }}/{{ item }}">{{ item|title }}</a></li>
        {% endfor %}
    </ul>
</li>

app/base/templates/site_template/sidebar.html
<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">
    <a href="{{ url_for("public_blueprint.route_default") }}" class="site_title"><i class="fa fa-spinner"></i> <span>Covid 19</span></a>
  </div>

  <div class="clearfix"></div>

{% if current_user.is_authenticated %}
  <!-- menu profile quick info -->
  <div class="profile clearfix">
    <div class="profile_pic">
      <img src="{{ url_for('static', filename='images/img.jpg') }}" alt="..." class="img-circle profile_img">
    </div>
    <div class="profile_info">
      <span>Welcome,</span>
      <h2> {{ current_user.username }} </h2>
    </div>
  </div>
  <!-- /menu profile quick info -->
{% endif %}
  <br />

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

  {% if not current_user.is_authenticated %}
      <div class="menu_section">
          <h3>General</h3>
          <ul class="nav side-menu">
              <li>
                  <a href="{{ url_for('public_blueprint.route_default') }}">
                      <i class="fa fa-line-chart"></i> România
                  </a>
              </li>

              <li>
                  <a href="{{ url_for('public_blueprint.compare') }}">
                      <i class="fa fa-bar-chart-o"></i> Compară țări
                  </a>
              </li>

              <li>
                  <a href="{{ url_for('public_blueprint.europe') }}">
                      <i class="fa fa-map-o"></i> Europa
                  </a>
              </li>
              <li>
                  <a href="{{ url_for('public_blueprint.global_map') }}">
                      <i class="fa fa-globe"></i> Global
                  </a>
              </li>
              <li>
                  <a>
                      <i class="fa fa-paper-plane-o"></i> Telegram
                      <span class="fa fa-chevron-down"></span>
                  </a>
                  <ul class="nav child_menu">
                      <li><a href="{{ url_for('redirects_views.home') }}" target="_blank">Alfred the Bot</a></li>
                      <li><a href="{{ url_for('redirects_views.channel') }}" target="_blank">#Covid-Updates</a></li>
                </ul>
            </li>
          </ul>
      </div>

  {% else %}
    <div class="menu_section">
      <h3>General</h3>
      <ul class="nav side-menu">
          {% with title="Home", icon="home", items=["index1", "index2", "index3"] %}
            {% include "site_template/parts/sidebar_item.html" %}
          {% endwith %}

          {% with title="Forms", icon="edit", items=["form", "form_advanced", "form_validation", "form_wizards", "form_upload", "form_buttons"] %}
              {% include "site_template/parts/sidebar_item.html" %}
          {% endwith %}

          {% with title="UI", icon="desktop", items=["general_elements", "media_gallery", "typography", "icons", "glyphicons", "widgets", "invoice", "inbox", "calendar"] %}
              {% include "site_template/parts/sidebar_item.html" %}
          {% endwith %}

          {% with title="Tables", icon="table", items=["tables", "tables_dynamic"] %}
            {% include "site_template/parts/sidebar_item.html" %}
          {% endwith %}

          {% with title="Data", icon="bar-chart-o", items=["chartjs", "chartjs2", "morisjs", "echarts", "other_charts"] %}
            {% include "site_template/parts/sidebar_item.html" %}
          {% endwith %}

      </ul>
    </div>
    <div class="menu_section">
      <h3>Live On</h3>
      <ul class="nav side-menu">

          {% with title="Additional", icon="bug", items=["ecommerce", "projects", "project_detail", "contacts", "profile", "pricing"] %}
            {% include "site_template/parts/sidebar_item.html" %}
          {% endwith %}

        <li><a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="/page_403">403 Error</a></li>
            <li><a href="/page_404">404 Error</a></li>
            <li><a href="/page_500">500 Error</a></li>
            <li><a href="/plain_page">Plain Page</a></li>
          </ul>
        </li>
        <li><a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
              <li><a href="#level1_1">Level One</a>
              <li><a>Level One<span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li class="sub_menu"><a href="/level2">Level Two</a>
                  </li>
                  <li><a href="#level2_1">Level Two</a>
                  </li>
                  <li><a href="#level2_2">Level Two</a>
                  </li>
                </ul>
              </li>
              <li><a href="#level1_2">Level One</a>
              </li>
          </ul>
        </li>
        <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a></li>
      </ul>
    </div>
  {% endif %}
  </div>
  <!-- /sidebar menu -->

  <!-- /menu footer buttons -->
  <div class="sidebar-footer hidden-small">
    <a data-toggle="tooltip" data-placement="top" title="Settings">
      <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
      <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Lock">
      <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Logout" href="{{ url_for('base_blueprint.logout') }}">
      <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
  </div>
  <!-- /menu footer buttons -->
</div>

app/base/templates/site_template/top_navigation.html
<div class="nav_menu">
  <nav>
    <div class="nav toggle">
      <a id="menu_toggle"><i class="fa fa-bars"></i></a>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <li class="">
        <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          <img src="{{ url_for('static', filename='images/img.jpg') }}" alt="">{{ current_user.username }}
          <span class=" fa fa-angle-down"></span>
        </a>
        <ul class="dropdown-menu dropdown-usermenu pull-right">
          <li><a href="javascript:;"> Profile</a></li>
          <li>
            <a href="javascript:;">
              <span class="badge bg-red pull-right">50%</span>
              <span>Settings</span>
            </a>
          </li>
          <li><a href="javascript:;">Help</a></li>
          <li><a href="{{ url_for('base_blueprint.logout') }}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
        </ul>
      </li>

      <li role="presentation" class="dropdown">
        <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
          <i class="fa fa-envelope-o"></i>
          <span class="badge bg-green">6</span>
        </a>
        <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
          <li>
            <a>
              <span class="image"><img src="{{ url_for('static', filename='images/img.jpg') }}" alt="Profile Image" /></span>
              <span>
                <span>John Doe</span>
                <span class="time">3 mins ago</span>
              </span>
              <span class="message">
                Film festivals used to be do-or-die moments for movie makers. They were where...
              </span>
            </a>
          </li>
          <li>
            <a>
              <span class="image"><img src="{{ url_for('static', filename='images/img.jpg') }}" alt="Profile Image" /></span>
              <span>
                <span>John Doe</span>
                <span class="time">3 mins ago</span>
              </span>
              <span class="message">
                Film festivals used to be do-or-die moments for movie makers. They were where...
              </span>
            </a>
          </li>
          <li>
            <a>
              <span class="image"><img src="{{ url_for('static', filename='images/img.jpg') }}" alt="Profile Image" /></span>
              <span>
                <span>John Doe</span>
                <span class="time">3 mins ago</span>
              </span>
              <span class="message">
                Film festivals used to be do-or-die moments for movie makers. They were where...
              </span>
            </a>
          </li>
          <li>
            <a>
              <span class="image"><img src="{{ url_for('static', filename='images/img.jpg') }}" alt="Profile Image" /></span>
              <span>
                <span>John Doe</span>
                <span class="time">3 mins ago</span>
              </span>
              <span class="message">
                Film festivals used to be do-or-die moments for movie makers. They were where...
              </span>
            </a>
          </li>
          <li>
            <div class="text-center">
              <a>
                <strong>See All Alerts</strong>
                <i class="fa fa-angle-right"></i>
              </a>
            </div>
          </li>
        </ul>
      </li>
    </ul>
  </nav>
</div>